In [1]:
import torch

In [4]:
x = torch.arange(20)
x[0], x[0:10]

(tensor(0), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [6]:
x.shape, x.numel() == x.shape[0]

(torch.Size([20]), True)

In [11]:
x.reshape(4, 5), x.shape

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 torch.Size([20]))

In [12]:
torch.ones((1, 3, 5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [13]:
torch.randn(1, 3, 5)

tensor([[[ 1.9268,  1.5723,  1.5922,  0.6602,  1.8076],
         [-0.3604, -0.2046, -0.6523, -1.6965, -0.4184],
         [ 0.1219, -0.2596, -0.1977,  0.4099,  1.1009]]])

In [14]:
torch.tensor([[2, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [24]:
X = torch.arange(20, dtype=torch.float32).reshape((1,4,5))
Y = torch.tensor([[[2.0, 1, 5, 4, 3], [1, 2, 3, 4, 5], [3, 2, 1, 4, 5], [5, 4, 3, 2, 1]]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.]],
 
         [[ 2.,  1.,  5.,  4.,  3.],
          [ 1.,  2.,  3.,  4.,  5.],
          [ 3.,  2.,  1.,  4.,  5.],
          [ 5.,  4.,  3.,  2.,  1.]]]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.],
          [ 2.,  1.,  5.,  4.,  3.],
          [ 1.,  2.,  3.,  4.,  5.],
          [ 3.,  2.,  1.,  4.,  5.],
          [ 5.,  4.,  3.,  2.,  1.]]]))

In [25]:
X == Y

tensor([[[False,  True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]])

In [26]:
X.sum()

tensor(190.)

In [27]:
X + Y

tensor([[[ 2.,  2.,  7.,  7.,  7.],
         [ 6.,  8., 10., 12., 14.],
         [13., 13., 13., 17., 19.],
         [20., 20., 20., 20., 20.]]])

In [28]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [31]:
c = torch.tensor([[1], [2], [3]])
d = torch.tensor([[1, 2]])

In [32]:
c * d

tensor([[1, 2],
        [2, 4],
        [3, 6]])

In [34]:
X

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]])

In [35]:
X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([], size=(0, 4, 5)))

In [ ]:
X.shape

torch.Size([1, 4, 5])

In [40]:
X[0, 1, 2] = 9

In [44]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [47]:
Z = torch.zeros_like(Y)
Z

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [50]:
print('id(Z) = ', id(Z))
Z[:] = X + Y
print('id(Z) = ', id(Z))
Z

id(Z) =  4712326032
id(Z) =  4712326032


tensor([[[ 2.,  4., 11., 13., 15.],
         [16., 20., 30., 28., 32.],
         [33., 35., 37., 43., 47.],
         [50., 52., 54., 56., 58.]]])

In [51]:
before = id(X)
X += Y
id(X) == before

True

In [53]:
A = X.numpy()
B = torch.tensor(A)

In [54]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [55]:
X == Y

tensor([[[ True, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]])

In [56]:
X < Y, X > Y

(tensor([[[False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False]]]),
 tensor([[[False,  True,  True,  True,  True],
          [ True,  True,  True,  True,  True],
          [ True,  True,  True,  True,  True],
          [ True,  True,  True,  True,  True]]]))