In [31]:
import torch

In [32]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y

tensor(5.)

In [33]:
x_ = torch.arange(5)
x_, x_[4], len(x_), x_.shape

(tensor([0, 1, 2, 3, 4]), tensor(4), 5, torch.Size([5]))

In [34]:
A = torch.arange(15).reshape(5,3)
A, A.T

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]),
 tensor([[ 0,  3,  6,  9, 12],
         [ 1,  4,  7, 10, 13],
         [ 2,  5,  8, 11, 14]]))

In [35]:
X = torch.arange(24).reshape(2,3,4)
X.shape

torch.Size([2, 3, 4])

In [36]:
A = torch.arange(30, dtype=torch.float64).reshape(5,6)
B = A.clone()
A * B

tensor([[  0.,   1.,   4.,   9.,  16.,  25.],
        [ 36.,  49.,  64.,  81., 100., 121.],
        [144., 169., 196., 225., 256., 289.],
        [324., 361., 400., 441., 484., 529.],
        [576., 625., 676., 729., 784., 841.]], dtype=torch.float64)

In [37]:
a = 2
a + A

tensor([[ 2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13.],
        [14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30., 31.]], dtype=torch.float64)

In [38]:
A.sum()

tensor(435., dtype=torch.float64)

In [39]:
A.sum(dim=0), A.sum(dim=1)

(tensor([60., 65., 70., 75., 80., 85.], dtype=torch.float64),
 tensor([ 15.,  51.,  87., 123., 159.], dtype=torch.float64))

In [40]:
C = torch.arange(60).reshape(3, 4, 5)
C.sum(dim=2).sum(dim=1)

tensor([190, 590, 990])

In [41]:
sum_A_keep = A.sum(dim=1, keepdim=True)
sum_A_keep, A / sum_A_keep

(tensor([[ 15.],
         [ 51.],
         [ 87.],
         [123.],
         [159.]], dtype=torch.float64),
 tensor([[0.0000, 0.0667, 0.1333, 0.2000, 0.2667, 0.3333],
         [0.1176, 0.1373, 0.1569, 0.1765, 0.1961, 0.2157],
         [0.1379, 0.1494, 0.1609, 0.1724, 0.1839, 0.1954],
         [0.1463, 0.1545, 0.1626, 0.1707, 0.1789, 0.1870],
         [0.1509, 0.1572, 0.1635, 0.1698, 0.1761, 0.1824]], dtype=torch.float64))

In [45]:
x = torch.arange(6, dtype=torch.float64)
y = torch.ones_like(x, dtype=torch.float64)
torch.dot(x, y), torch.mv(A, x)


(tensor(15., dtype=torch.float64),
 tensor([ 55., 145., 235., 325., 415.], dtype=torch.float64))

In [54]:
B = torch.ones(6, 6, dtype=torch.float64)
A, B

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.],
         [24., 25., 26., 27., 28., 29.]], dtype=torch.float64),
 tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]], dtype=torch.float64))

In [55]:
torch.mm(A, B)

tensor([[ 15.,  15.,  15.,  15.,  15.,  15.],
        [ 51.,  51.,  51.,  51.,  51.,  51.],
        [ 87.,  87.,  87.,  87.,  87.,  87.],
        [123., 123., 123., 123., 123., 123.],
        [159., 159., 159., 159., 159., 159.]], dtype=torch.float64)

In [56]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()

(tensor(5.), tensor(7.))

In [57]:
mat = torch.ones((2,2))
torch.norm(mat)

tensor(2.)

In [59]:
mat1 = torch.tensor([[1, 2, 3], [3, 4 ,5.]])
torch.norm(mat1)

tensor(8.)

In [60]:
import torch

A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])

# 方式 1：使用 PyTorch 内置函数
print("F 范数:", torch.norm(A)) # 结果: sqrt(1^2 + 2^2 + 3^2 + 4^2) = sqrt(30) ≈ 5.4772

# 方式 2：手动计算验证
print("验证:", torch.sqrt(torch.sum(A**2))) # 5.4772


F 范数: tensor(5.4772)
验证: tensor(5.4772)


In [61]:
import torch

# 假设有一个权重向量 w
w = torch.tensor([3.0, -4.0])

# 1. L2 范数 (默认)
l2 = torch.norm(w, p=2)  # 或 torch.linalg.vector_norm(w, ord=2)
print("L2 范数:", l2)     # sqrt(3^2 + (-4)^2) = 5.0

# 2. L1 范数
l1 = torch.norm(w, p=1)  # |3| + |-4|
print("L1 范数:", l1)     # 7.0

# 3. L_infinity 范数
l_inf = torch.norm(w, p=float('inf'))
print("L_inf 范数:", l_inf) # max(3, 4) = 4.0


L2 范数: tensor(5.)
L1 范数: tensor(7.)
L_inf 范数: tensor(4.)
