In [37]:
import torch

In [38]:
num_inputs, num_outputs, num_samples = 784, 3, 1000
X = torch.randn(num_samples, num_inputs)
y = torch.randint(0, num_outputs, (num_samples, ))
X, y

(tensor([[ 0.1375,  0.5460,  0.1879,  ..., -2.2166,  0.3552,  0.6671],
         [ 1.0268,  0.9541, -0.4628,  ...,  0.5820,  1.1972, -1.5455],
         [-0.7065, -0.4856, -0.3197,  ...,  1.0775,  1.3453, -0.3955],
         ...,
         [ 0.5154, -0.5428,  0.3636,  ...,  0.0993,  0.7341, -1.0279],
         [ 1.1160,  0.6765,  0.2865,  ...,  0.2724, -1.5266, -0.1580],
         [-1.4005,  0.0400,  0.8726,  ..., -0.4966,  0.3457, -1.0394]]),
 tensor([1, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 0, 0, 0,
         2, 2, 2, 0, 1, 2, 0, 1, 1, 2, 1, 2, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 2,
         1, 1, 0, 0, 0, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1, 2, 1, 1,
         2, 1, 1, 2, 2, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 0, 0, 1, 0, 2, 2, 2,
         2, 0, 0, 1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 2,
         2, 0, 2, 2, 2, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1,
         1, 0, 1, 0, 2, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 0, 1, 1, 2, 2, 

In [39]:
W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)
W, b

(tensor([[ 0.0035, -0.0035,  0.0028],
         [-0.0039, -0.0142, -0.0015],
         [-0.0003, -0.0089, -0.0115],
         ...,
         [-0.0011,  0.0096,  0.0205],
         [-0.0160,  0.0022, -0.0079],
         [ 0.0077,  0.0135,  0.0023]], requires_grad=True),
 tensor([0., 0., 0.], requires_grad=True))

In [40]:
def softmax(O):
    O_max = torch.max(O, dim=1, keepdim=True).values
    exp_O = torch.exp(O - O_max)
    partition = exp_O.sum(dim=1, keepdim=True)
    return exp_O / partition

In [41]:
def reg(X):
    return softmax(X @ W + b)

In [42]:
def cross_entropy(y_, y):
    return - torch.log(y_[range(len(y_)), y] + 1e-7)

In [49]:
lr, batch_size, eps = 0.1, 32, 1000

In [50]:
for ep in range(eps):
    inds = torch.randperm(eps)
    for i in range(0, num_samples, batch_size):
        batch_idx = inds[i : i + batch_size]
        X_batch = X[batch_idx]
        y_batch = y[batch_idx]

        y_ = reg(X_batch)
        loss = cross_entropy(y_, y_batch).mean()
        loss.backward()

        with torch.no_grad():
            W -= lr * W.grad
            b -= lr * b.grad

            W.grad.zero_()
            b.grad.zero_()

    with torch.no_grad():
        all_y_hat = reg(X)
        preds = all_y_hat.argmax(dim=1)
        acc = (preds == y).float().mean()
        total_loss = cross_entropy(all_y_hat, y).mean()
        print(f"Ep {ep+1:2d} | Loss:{total_loss.item():.4f} | Acc:{acc.item() * 100:.2f}%")


Ep  1 | Loss:0.6001 | Acc:76.70%
Ep  2 | Loss:0.4360 | Acc:82.90%
Ep  3 | Loss:0.3002 | Acc:92.30%
Ep  4 | Loss:0.2878 | Acc:90.70%
Ep  5 | Loss:0.2138 | Acc:95.70%
Ep  6 | Loss:0.1711 | Acc:98.00%
Ep  7 | Loss:0.1419 | Acc:99.20%
Ep  8 | Loss:0.1243 | Acc:99.80%
Ep  9 | Loss:0.1097 | Acc:100.00%
Ep 10 | Loss:0.0968 | Acc:100.00%
Ep 11 | Loss:0.0933 | Acc:100.00%
Ep 12 | Loss:0.0862 | Acc:100.00%
Ep 13 | Loss:0.0807 | Acc:100.00%
Ep 14 | Loss:0.0746 | Acc:100.00%
Ep 15 | Loss:0.0687 | Acc:100.00%
Ep 16 | Loss:0.0640 | Acc:100.00%
Ep 17 | Loss:0.0607 | Acc:100.00%
Ep 18 | Loss:0.0577 | Acc:100.00%
Ep 19 | Loss:0.0554 | Acc:100.00%
Ep 20 | Loss:0.0524 | Acc:100.00%
Ep 21 | Loss:0.0500 | Acc:100.00%
Ep 22 | Loss:0.0484 | Acc:100.00%
Ep 23 | Loss:0.0465 | Acc:100.00%
Ep 24 | Loss:0.0450 | Acc:100.00%
Ep 25 | Loss:0.0432 | Acc:100.00%
Ep 26 | Loss:0.0419 | Acc:100.00%
Ep 27 | Loss:0.0405 | Acc:100.00%
Ep 28 | Loss:0.0394 | Acc:100.00%
Ep 29 | Loss:0.0382 | Acc:100.00%
Ep 30 | Loss:0.0371 | 

In [51]:
import numpy as np

In [52]:
def softmax(Z):
    z_max = np.max(Z, axis=1, keepdims=True)
    exp_Z = np.exp(Z - z_max)
    sum_exp_Z = np.sum(exp_Z, axis=1, keepdims=True)
    return exp_Z / sum_exp_Z

In [58]:
Z = np.array([[3, 4, 1],[4, 2, 3], [3, 3, 1]])
Z_max = np.max(Z, axis=1, keepdims=True)
Z, Z_max

(array([[3, 4, 1],
        [4, 2, 3],
        [3, 3, 1]]),
 array([[4],
        [4],
        [3]]))

In [60]:
exp_Z = np.exp(Z - Z_max)
exp_Z

array([[0.36787944, 1.        , 0.04978707],
       [1.        , 0.13533528, 0.36787944],
       [1.        , 1.        , 0.13533528]])

In [61]:
sum_exp_Z = np.sum(exp_Z, axis=1, keepdims=True)
sum_exp_Z

array([[1.41766651],
       [1.50321472],
       [2.13533528]])

In [62]:
A = exp_Z / sum_exp_Z
A

array([[0.25949646, 0.70538451, 0.03511903],
       [0.66524096, 0.09003057, 0.24472847],
       [0.46831053, 0.46831053, 0.06337894]])

In [67]:
import numpy as np

# 1. 设定随机种子与生成合成数据
np.random.seed(42)
N = 100  # 样本数
D = 3    # 特征数

# 真实参数 (目标: 算法应该学习出接近这些值的 W 和 b)
true_W = np.array([[2.0], [-1.5], [0.5]]) # (3, 1)
true_b = 3.0                              # 标量

# 生成输入 X (100, 3) 和 带有噪声的标签 Y (100, 1)
X = np.random.randn(N, D)
Y = X @ true_W + true_b + np.random.randn(N, 1) * 0.1

# 2. 初始化模型参数 (W, b)
W = np.random.randn(D, 1) * 0.01  # (3, 1)
b = np.zeros((1, 1))              # (1, 1)

# 3. 超参数设置
learning_rate = 0.1
epochs = 200

print("--- 开始训练 ---")
for epoch in range(epochs):
    # ====================================================
    # A. 前向传播 (Forward Pass)
    # ====================================================
    # 1) 矩阵相乘 + 广播加偏置: (100, 3) @ (3, 1) + (1, 1) -> (100, 1)
    Z = np.dot(X, W) + b
    
    # 2) 计算 MSE Loss: 标量
    loss = np.mean((Z - Y) ** 2) / 2.0
    
    # ====================================================
    # B. 反向传播 (Backward Pass - 链式法则传递梯度)
    # ====================================================
    # Step 1: dL / dZ (损失关于预测值 Z 的梯度)
    # 数学公式: dZ = (Z - Y) / N
    dZ = (Z - Y) / N   # (100, 1)
    
    # Step 2: dL / dW (上游梯度 dZ 乘以 dZ/dW，即 X^T)
    # 数学公式: dW = X^T @ dZ
    dW = np.dot(X.T, dZ) # (3, 100) @ (100, 1) -> (3, 1)
    
    # Step 3: dL / db (偏置项沿 Batch 维度累加)
    # 数学公式: db = sum(dZ)
    db = np.sum(dZ, axis=0, keepdims=True) # (1, 1)
    
    # ====================================================
    # C. 参数更新 (Gradient Descent)
    # ====================================================
    W -= learning_rate * dW
    b -= learning_rate * db
    
    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1:2d} | Loss: {loss:.6f}")

print("\n--- 训练结束，拟合结果对比 ---")
print("真实 W:\n", true_W.ravel())
print("学到的 W:\n", W.ravel())
print(f"真实 b: {true_b:.2f} | 学到的 b: {b.item():.2f}")

--- 开始训练 ---
Epoch  1 | Loss: 8.830930
Epoch  5 | Loss: 3.302155
Epoch 10 | Loss: 1.015385
Epoch 15 | Loss: 0.334533
Epoch 20 | Loss: 0.120158
Epoch 25 | Loss: 0.048053
Epoch 30 | Loss: 0.021940
Epoch 35 | Loss: 0.011733
Epoch 40 | Loss: 0.007448
Epoch 45 | Loss: 0.005539
Epoch 50 | Loss: 0.004647
Epoch 55 | Loss: 0.004216
Epoch 60 | Loss: 0.004003
Epoch 65 | Loss: 0.003896
Epoch 70 | Loss: 0.003841
Epoch 75 | Loss: 0.003813
Epoch 80 | Loss: 0.003799
Epoch 85 | Loss: 0.003792
Epoch 90 | Loss: 0.003788
Epoch 95 | Loss: 0.003786
Epoch 100 | Loss: 0.003785
Epoch 105 | Loss: 0.003784
Epoch 110 | Loss: 0.003784
Epoch 115 | Loss: 0.003784
Epoch 120 | Loss: 0.003784
Epoch 125 | Loss: 0.003784
Epoch 130 | Loss: 0.003784
Epoch 135 | Loss: 0.003784
Epoch 140 | Loss: 0.003784
Epoch 145 | Loss: 0.003784
Epoch 150 | Loss: 0.003784
Epoch 155 | Loss: 0.003784
Epoch 160 | Loss: 0.003784
Epoch 165 | Loss: 0.003784
Epoch 170 | Loss: 0.003784
Epoch 175 | Loss: 0.003784
Epoch 180 | Loss: 0.003784
Epoch 18

In [75]:
X[13] @ W + b, Y[13]

(array([[2.3759303]]), array([2.45305771]))